package com.newspace.overdraftproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class samplenew implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public samplenew() {
    }




}